### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by TTFMF**
I do not take credit for this XDF. The credit belongs to a user on the Gearhead-EFI forum...Link below. I only decrypted the file so users of the XDF can doublecheck address ranges and conversions before making changes to their .bin with this XDF. I haven't gone over the xdf, yet, but I heard it's been tested and confirmed good, so far. If this file is not welcome, please disregard this pull request.

http://www.gearhead-efi.com/Fuel-Injection/showthread.php?5894-2002-OS-12212156-xdf

### CODE REVIEW

**Comment by TTFMF** [comment]
I also removed the password to more files that I suspect were the ones belonging to a member of the community that has vanished. I read that the creator of these XDFs vanished from tuning community. There are many users in the community that wish to continue the work done by the creator of these XDFs, so I removed the modify passwords from them.

**Comment by robbranam** [comment]
Thats great, but i dont understand how to download these files??

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 19:53, ***@***.***> wrote:   


I also removed the password to more files that I suspect were the ones belonging to a member of the community that has vanished. I read that the creator of these XDFs vanished from tuning community. There are many users in the community that wish to continue the work done by the creator of these XDFs, so I removed the modify passwords from them.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TTFMF** [comment]
First you merge/commit the pull request. Then you can select view raw data and save as to download the ones you want. Hithub is weird about downloading what is essentily a text file. You can also download your whole repository from the main tree I think.

**Comment by Snoman002** [comment]
Great work, sorry for the delay

**Pull request merged**
